### ISSUE TITLE
UI breaks in mobile view

### ISSUE THREAD

**Issue by akshaybabloo** [timcreative/paper-bootstrap-wizard#1]
I was looking at the demo of the wizard, this http://demos.creative-tim.com/paper-bootstrap-wizard/wizard-list-place.html one breaks as in the bubbles are all scattered around the screen.  See the screenshot. 
![screenshot_20160922-064203](https://cloud.githubusercontent.com/assets/7360286/18724234/ce475f24-808f-11e6-812b-e6100bcbab7b.png)

**Comment by alexandru-paduraru** [comment]
@akshaybabloo thank you for checking our product. We've worked so hard to develop that random generator of the bubbles all around the screen, now we have to remove it. Just kidding :-)), we will check this and fix it ASAP. Thank you again for pointing out! Stay tuned for an update in the next days.

**Comment by Evilopeth** [comment]
Hello Guys any updates on this problem cause i have been having the same problem here :((

**Comment by alexandru-paduraru** [comment]
@akshaybabloo @Evilopeth it seems we updated the product but didn't send it to our live server... :-( please download again the v1.0.1 and everything will be working fine there. 

Best,
Alex
